# toml syntax highlight
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# typescript syntax highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'
hook_source = '''
let g:typescript_indent_disable = 1
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = 'typescriptreact'
hook_source = '''
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx
'''

# html5 syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'
hook_source = '''
let g:html5_event_handler_attributes_complete = 1
let g:html5_rdfa_attributes_complete = 1
let g:html5_microdata_attributes_complete = 1
let g:html5_aria_attributes_complete = 1
'''

# js library syntax
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
hook_source = '''
let g:used_javascript_libs = 'vue,react,flux,jquery,jasmin,angularjs,angularui,angularuirouter'
autocmd BufReadPre *.js let b:javascript_lib_use_jquery = 1
autocmd BufReadPre *.js let b:javascript_lib_use_react = 1
autocmd BufReadPre *.tsx let b:javascript_lib_use_react = 1
autocmd BufReadPre *.ts let b:javascript_lib_use_angularjs = 1
autocmd BufReadPre *.vue let b:javascript_lib_use_vue = 1
'''
on_ft = 'javascript'

# jsx syntax
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = 'javascript'

# python autocomplete jedi
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

# elixir
[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = 'elixir'

# ruby
# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = 'ruby'
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

# slim
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'vim-scripts/SQLUtilities'
on_ft = 'sql'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
